# Generated by Django 5.0.7 on 2024-08-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('releases', '0002_remove_release_artist_release_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites_list',
            field=models.ManyToManyField(blank=True, null=True, to='releases.release'),
        ),
    ]
