# Generated by Django 5.0.7 on 2024-08-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_favorites_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorites_list',
            new_name='favoriteslist',
        ),
    ]
