# Generated by Django 5.0.7 on 2024-08-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_favorites_list_profile_favoriteslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favoriteslist',
            new_name='favorites_list',
        ),
    ]
