# Generated by Django 5.0.7 on 2024-08-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_favoriteslist_profile_favorites_list'),
        ('releases', '0002_remove_release_artist_release_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites_list',
            field=models.ManyToManyField(blank=True, related_name='favorites_list', to='releases.release'),
        ),
    ]
