# Generated by Django 5.0.7 on 2024-09-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_favorites_list'),
        ('releases', '0004_alter_release_options_alter_release_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_activation_code',
            field=models.CharField(max_length=255, verbose_name='کد فعالسازی ایمیل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites_list',
            field=models.ManyToManyField(blank=True, related_name='favorites_list', to='releases.release', verbose_name='لیست علاقه\u200cمندی ها'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='related_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, verbose_name='نام کاربری'),
        ),
    ]
