# Generated by Django 5.0.7 on 2024-08-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='in_progress',
        ),
    ]
