# Generated by Django 5.0.7 on 2024-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
