# Generated by Django 5.0.7 on 2024-08-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='artist',
        ),
        migrations.AddField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
    ]
