# Generated by Django 5.0.7 on 2024-08-31 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_remove_release_artist_release_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='audio_file',
            field=models.FileField(upload_to='releases/audios', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
    ]
