# Generated by Django 5.0.7 on 2024-09-17 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_options_alter_artist_description_and_more'),
        ('releases', '0003_alter_release_audio_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'verbose_name': 'منتشر شده', 'verbose_name_plural': 'منتشر شده ها'},
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='هنرمند'),
        ),
        migrations.AlterField(
            model_name='release',
            name='audio_file',
            field=models.FileField(upload_to='releases/audios', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='release',
            name='cover_art',
            field=models.ImageField(upload_to='releases/covers', verbose_name='کاور'),
        ),
        migrations.AlterField(
            model_name='release',
            name='slug',
            field=models.SlugField(verbose_name='پیوندک'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='release',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید'),
        ),
    ]
