# Generated by Django 5.0.7 on 2024-12-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_options_alter_artist_description_and_more'),
        ('releases', '0004_alter_release_options_alter_release_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='features',
            field=models.ManyToManyField(related_name='features', to='artists.artist', verbose_name='همکاری ها'),
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_artist', to='artists.artist', verbose_name='هنرمند'),
        ),
    ]
