# Generated by Django 5.0.7 on 2024-08-28 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_alter_article_article_date'),
        ('releases', '0002_remove_release_artist_release_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('comment_date', models.DateTimeField()),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('related_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='releases.release')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
