# Generated by Django 5.0.7 on 2024-09-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_comment_date'),
        ('news', '0003_alter_article_options_alter_article_content_and_more'),
        ('releases', '0004_alter_release_options_alter_release_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AddField(
            model_name='comment',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=255, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='related_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.article', verbose_name='مقاله مرتبط'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='related_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='releases.release', verbose_name='موزیک مرتبط'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط'),
        ),
    ]
