# Generated by Django 5.0.7 on 2024-08-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ContactUsMessage',
        ),
    ]
