# Generated by Django 5.0.7 on 2024-09-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_message_contactusmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmessage',
            options={'verbose_name': 'پیام تماس با ما', 'verbose_name_plural': 'پبام های تماس با ما'},
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='admin_response',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین'),
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='is_read_by_admin',
            field=models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='subject',
            field=models.CharField(max_length=120, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
