# Generated by Django 5.0.7 on 2024-08-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RulesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(upload_to='home')),
                ('first_subject', models.CharField(max_length=255)),
                ('first_text', models.CharField(max_length=255)),
                ('second_image', models.ImageField(upload_to='home')),
                ('second_subject', models.CharField(max_length=255)),
                ('second_text', models.CharField(max_length=255)),
                ('third_image', models.ImageField(upload_to='home')),
                ('third_subject', models.CharField(max_length=255)),
                ('third_text', models.CharField(max_length=255)),
            ],
        ),
    ]
