# Generated by Django 5.0.7 on 2024-08-31 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_logo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserTabInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('icon', models.FileField(upload_to='home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])])),
            ],
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.FileField(upload_to='home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'])]),
        ),
    ]
