# Generated by Django 5.0.7 on 2024-09-17 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_browsertabinfo_alter_logo_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutustext',
            options={'verbose_name': 'متن درباره ما', 'verbose_name_plural': 'متن های درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='browsertabinfo',
            options={'verbose_name': 'اطلاعات', 'verbose_name_plural': 'اطلاعات تب مرورگر'},
        ),
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'اطلاعات', 'verbose_name_plural': 'اطلاعات فوتر'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'لوگو', 'verbose_name_plural': 'لوگو ها'},
        ),
        migrations.AlterModelOptions(
            name='rulestext',
            options={'verbose_name': 'متن قوانین و مقررات', 'verbose_name_plural': 'متن های قوانین و مقررات'},
        ),
        migrations.AlterModelOptions(
            name='slidershow',
            options={'verbose_name': 'اسلایدر شو', 'verbose_name_plural': 'اسلایدر شو ها'},
        ),
        migrations.AlterField(
            model_name='aboutustext',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='browsertabinfo',
            name='icon',
            field=models.FileField(upload_to='home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='browsertabinfo',
            name='text',
            field=models.CharField(max_length=255, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='facebook',
            field=models.CharField(max_length=255, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='instagram',
            field=models.CharField(max_length=255, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='telephone',
            field=models.CharField(max_length=255, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='text',
            field=models.CharField(max_length=255, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='twitter',
            field=models.CharField(max_length=255, verbose_name='توئیتر'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='youtube',
            field=models.CharField(max_length=255, verbose_name='یوتیوب'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.FileField(upload_to='home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'])], verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='rulestext',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='first_image',
            field=models.ImageField(upload_to='home', verbose_name='تصویر اول'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='first_subject',
            field=models.CharField(max_length=255, verbose_name='موضوع اول'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='first_text',
            field=models.CharField(max_length=255, verbose_name='متن اول'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='second_image',
            field=models.ImageField(upload_to='home', verbose_name='تصویر دوم'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='second_subject',
            field=models.CharField(max_length=255, verbose_name='موضوع دوم'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='second_text',
            field=models.CharField(max_length=255, verbose_name='متن دوم'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='third_image',
            field=models.ImageField(upload_to='home', verbose_name='تصویر سوم'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='third_subject',
            field=models.CharField(max_length=255, verbose_name='موضوع سوم'),
        ),
        migrations.AlterField(
            model_name='slidershow',
            name='third_text',
            field=models.CharField(max_length=255, verbose_name='متن سوم'),
        ),
    ]
