# Generated by Django 5.0.7 on 2024-09-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'هنرمند', 'verbose_name_plural': 'هنرمندان'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='artists', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='نام مستعار'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(verbose_name='پیوندک'),
        ),
    ]
